import { useState, type ReactNode } from "react";
import type { TaskKind, TaskPeriod } from "@/types/crm";
import styles from "./tasks.module.css";

export interface NewTaskDraft { title: string; kind: TaskKind; period: Exclude<TaskPeriod, "completed" | "overdue">; dueTime: string; assignee: string; contactName: string; dealTitle: string; }

export function NewTaskModal({ onCreate, onClose }: { onCreate: (draft: NewTaskDraft) => void; onClose: () => void }) {
  const [draft, setDraft] = useState<NewTaskDraft>({ title: "", kind: "Звонок", period: "today", dueTime: "", assignee: "Георгий", contactName: "", dealTitle: "" });
  const update = (patch: Partial<NewTaskDraft>) => setDraft((current) => ({ ...current, ...patch }));
  return <div className={styles.modalLayer}><button className={styles.backdrop} type="button" onClick={onClose} aria-label="Закрыть создание задачи" /><form className={styles.newTaskModal} onSubmit={(event) => { event.preventDefault(); if (draft.title.trim()) onCreate(draft); }} onKeyDown={(event) => { const target = event.target as HTMLElement; if (event.key === "Enter" && target.tagName !== "TEXTAREA" && target.getAttribute("type") !== "submit") event.preventDefault(); }}><header><div><span>Новая задача</span><h2>Запланировать действие</h2></div><button type="button" onClick={onClose} aria-label="Закрыть">×</button></header><div className={styles.newTaskBody}><Field label="Что необходимо сделать" required><input autoFocus aria-label="Что необходимо сделать" value={draft.title} onChange={(event) => update({ title: event.target.value })} placeholder="Например, позвонить клиенту" /></Field><div className={styles.formGrid}><Field label="Тип действия"><select value={draft.kind} onChange={(event) => update({ kind: event.target.value as TaskKind })}><option>Звонок</option><option>Встреча</option><option>Сообщение</option><option>Другое</option></select></Field><Field label="Ответственный"><select value={draft.assignee} onChange={(event) => update({ assignee: event.target.value })}><option>Георгий</option><option>Елена</option><option>Андрей</option></select></Field><Field label="Срок"><select value={draft.period} onChange={(event) => update({ period: event.target.value as "today" | "upcoming" })}><option value="today">Сегодня</option><option value="upcoming">Предстоящая</option></select></Field><Field label="Время"><input type="time" value={draft.dueTime} onChange={(event) => update({ dueTime: event.target.value })} /></Field></div><Field label="Контакт"><input value={draft.contactName} onChange={(event) => update({ contactName: event.target.value })} placeholder="Имя клиента — необязательно" /></Field><Field label="Сделка"><input value={draft.dealTitle} onChange={(event) => update({ dealTitle: event.target.value })} placeholder="Связанная сделка — необязательно" /></Field></div><footer><button type="button" onClick={onClose}>Отмена</button><button className={styles.primaryButton} type="submit" disabled={!draft.title.trim()}>Создать задачу</button></footer></form></div>;
}

function Field({ label, required = false, children }: { label: string; required?: boolean; children: ReactNode }) { return <label className={styles.field}><span>{label}{required && <b>обязательно</b>}</span>{children}</label>; }
