"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import styles from "./settings.module.css";

type Section = "workspace" | "pipeline" | "tasks" | "integrations" | "team" | "notifications" | "security" | "data" | "profile";
type PipelineStageDraft = { id?: string; key: string; title: string; color: string; dealCount: number };
type ApiTaskKind = "CALL" | "MEETING" | "MESSAGE" | "OTHER";
type TaskTypeDraft = { id?: string; key: string; name: string; baseKind: ApiTaskKind; position: number; isActive: boolean; taskCount: number };
type TeamMemberSummary = { id: string; name: string; email: string; role: "ADMIN" | "LEAD" | "MANAGER"; status: "ACTIVE" | "INVITED" | "SUSPENDED" };
type IntegrationState = { provider: string; status: "READY" | "CREDENTIALS_REQUIRED" | "CONNECTED" | "ERROR"; enabled: boolean; lastEventAt: string | null; lastError: string | null; processedCount: number };

const stageColors = ["#d6a835", "#d98245", "#d35f63", "#5d8fc9", "#4f9dd5", "#8b6cc2", "#4a9d75", "#55b89b", "#b76ac8", "#76767a"];
const taskKindLabels: Record<ApiTaskKind, string> = { CALL: "Звонок", MEETING: "Встреча", MESSAGE: "Сообщение", OTHER: "Другое действие" };
const roleLabels = { ADMIN: "Администратор", LEAD: "Руководитель", MANAGER: "Менеджер" } as const;
const navigation: { group: string; items: { id: Section; label: string; icon: string }[] }[] = [
  { group: "Основное", items: [{ id: "workspace", label: "Рабочее пространство", icon: "◇" }] },
  { group: "Рабочие процессы", items: [{ id: "pipeline", label: "Воронка", icon: "▥" }, { id: "tasks", label: "Типы задач", icon: "✓" }] },
  { group: "Коммуникации", items: [{ id: "integrations", label: "Интеграции", icon: "↗" }, { id: "notifications", label: "Уведомления", icon: "◉" }] },
  { group: "Команда", items: [{ id: "team", label: "Участники и роли", icon: "♙" }] },
  { group: "Система", items: [{ id: "security", label: "Безопасность", icon: "⌾" }, { id: "data", label: "Данные", icon: "⇅" }] },
  { group: "Личное", items: [{ id: "profile", label: "Мой профиль", icon: "○" }] },
];

function stageKey(id?: string) { return id || `new-${crypto.randomUUID()}`; }

export function SettingsCenter() {
  const [section, setSection] = useState<Section>("workspace");
  const [notice, setNotice] = useState("");
  const notify = useCallback((message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); }, []);
  return <section className={styles.page}>
    <header className={styles.topbar}><div><span>Администрирование</span><h1>Настройки</h1></div></header>
    <div className={styles.settingsLayout}>
      <aside className={styles.settingsNav}>{navigation.map((group) => <section key={group.group}><span>{group.group}</span>{group.items.map((item) => <button className={section === item.id ? styles.activeNav : ""} type="button" onClick={() => setSection(item.id)} key={item.id}><i>{item.icon}</i>{item.label}</button>)}</section>)}</aside>
      <div className={styles.content}>
        {section === "workspace" && <WorkspaceSettings onNotify={notify} />}
        {section === "pipeline" && <PipelineSettings onNotify={notify} />}
        {section === "tasks" && <TaskTypesSettings onNotify={notify} />}
        {section === "integrations" && <IntegrationSettings />}
        {section === "notifications" && <NotificationsSettings />}
        {section === "team" && <TeamAccessSettings />}
        {section === "security" && <SecuritySettings onNotify={notify} />}
        {section === "data" && <DataSettings />}
        {section === "profile" && <ProfileSettings onNotify={notify} />}
      </div>
    </div>
    {notice && <div className={styles.notice} role="status">✓ {notice}</div>}
  </section>;
}

function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className={styles.pageIntro}><span>{eyebrow}</span><h2>{title}</h2><p>{description}</p></header>; }

function PipelineSettings({ onNotify }: { onNotify: (message: string) => void }) {
  const [stages, setStages] = useState<PipelineStageDraft[]>([]); const [saved, setSaved] = useState<PipelineStageDraft[]>([]); const [loadState, setLoadState] = useState<"loading" | "ready" | "error">("loading"); const [saving, setSaving] = useState(false); const [colorPickerKey, setColorPickerKey] = useState<string | null>(null);
  const changed = JSON.stringify(stages) !== JSON.stringify(saved);
  useEffect(() => { let active = true; void fetch("/api/crm/pipeline/configuration", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { pipeline?: { stages: Array<{ id: string; title: string; color: string; dealCount: number }> }; message?: string }; if (!response.ok || !payload.pipeline) throw new Error(payload.message); if (!active) return; const next = payload.pipeline.stages.map((stage) => ({ ...stage, key: stageKey(stage.id) })); setStages(next); setSaved(next); setLoadState("ready"); }).catch(() => { if (active) setLoadState("error"); }); return () => { active = false; }; }, []);
  function move(index: number, direction: -1 | 1) { const nextIndex = index + direction; if (nextIndex < 0 || nextIndex >= stages.length) return; const next = [...stages]; [next[index], next[nextIndex]] = [next[nextIndex]!, next[index]!]; setStages(next); }
  async function save() { if (stages.some((stage) => !stage.title.trim())) return onNotify("Укажите название каждого этапа"); setSaving(true); try { const response = await fetch("/api/crm/pipeline/configuration", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ stages: stages.map(({ id, title, color }) => ({ id, title: title.trim(), color })) }) }); const payload = await response.json() as { pipeline?: { stages: Array<{ id: string; title: string; color: string; dealCount: number }> }; message?: string }; if (!response.ok || !payload.pipeline) throw new Error(payload.message || "Не удалось сохранить воронку"); const next = payload.pipeline.stages.map((stage) => ({ ...stage, key: stageKey(stage.id) })); setStages(next); setSaved(next); onNotify("Этапы воронки сохранены"); } catch (error) { onNotify(error instanceof Error ? error.message : "Не удалось сохранить воронку"); } finally { setSaving(false); } }
  return <main><PageIntro eyebrow="Рабочий процесс" title="Воронка" description="Этапы, по которым движется сделка от нового обращения до результата." /><section className={styles.moduleEditor}><header><div className={styles.moduleTitle}><i>▥</i><span><small>Настраивается для всей команды</small><strong>Этапы продаж</strong></span></div></header><div className={styles.fieldHeader}><div><strong>Этапы воронки</strong><span>Порядок сразу используется на доске сделок.</span></div><button type="button" disabled={loadState !== "ready"} onClick={() => setStages((current) => [...current, { key: stageKey(), title: "Новый этап", color: stageColors[current.length % stageColors.length]!, dealCount: 0 }])}>＋ Добавить этап</button></div>{loadState === "loading" ? <div className={styles.editorState}>Загружаем этапы…</div> : loadState === "error" ? <div className={styles.editorState}>Не удалось загрузить этапы. Обновите страницу.</div> : <div className={`${styles.fieldList} ${styles.stageFieldList}`}>{stages.map((stage, index) => <div key={stage.key}><span className={styles.drag}>⠿</span><input aria-label={`Название этапа ${index + 1}`} value={stage.title} onChange={(event) => setStages((current) => current.map((item) => item.key === stage.key ? { ...item, title: event.target.value } : item))} /><div className={styles.stageColorWrap}><button className={styles.stageColorButton} type="button" aria-label={`Цвет этапа ${stage.title}`} style={{ backgroundColor: stage.color }} onClick={() => setColorPickerKey((current) => current === stage.key ? null : stage.key)} />{colorPickerKey === stage.key && <div className={styles.colorPalette}>{stageColors.map((color) => <button className={stage.color === color ? styles.selectedColor : ""} type="button" aria-label={`Выбрать цвет ${color}`} style={{ backgroundColor: color }} onClick={() => { setStages((current) => current.map((item) => item.key === stage.key ? { ...item, color } : item)); setColorPickerKey(null); }} key={color} />)}</div>}</div><span className={styles.fieldType}>{stage.dealCount ? `${stage.dealCount} сделок` : "Этап"}</span><div className={styles.rowActions}><button type="button" disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button type="button" disabled={index === stages.length - 1} onClick={() => move(index, 1)}>↓</button><button className={styles.removeButton} type="button" disabled={stages.length === 1 || stage.dealCount > 0} title={stage.dealCount ? "Сначала перенесите сделки" : undefined} onClick={() => setStages((current) => current.filter((item) => item.key !== stage.key))}>×</button></div></div>)}</div>}{changed && <footer><button type="button" onClick={() => setStages(saved)}>Отменить</button><button className={styles.footerSaveButton} type="button" disabled={saving} onClick={() => { void save(); }}>{saving ? "Сохраняем…" : "Сохранить изменения"}</button></footer>}</section></main>;
}

function TaskTypesSettings({ onNotify }: { onNotify: (message: string) => void }) {
  const [items, setItems] = useState<TaskTypeDraft[]>([]); const [saved, setSaved] = useState<TaskTypeDraft[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const changed = JSON.stringify(items) !== JSON.stringify(saved);
  useEffect(() => { let active = true; void fetch("/api/crm/settings/task-types", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { taskTypes?: TaskTypeDraft[]; message?: string }; if (!response.ok || !payload.taskTypes) throw new Error(payload.message); if (active) { setItems(payload.taskTypes); setSaved(payload.taskTypes); } }).catch(() => onNotify("Не удалось загрузить типы задач")).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [onNotify]);
  function move(index: number, direction: -1 | 1) { const nextIndex = index + direction; if (nextIndex < 0 || nextIndex >= items.length) return; const next = [...items]; [next[index], next[nextIndex]] = [next[nextIndex]!, next[index]!]; setItems(next.map((item, position) => ({ ...item, position }))); }
  async function save() { setSaving(true); try { const response = await fetch("/api/crm/settings/task-types", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ taskTypes: items.map(({ id, name, baseKind, isActive }) => ({ id, name: name.trim(), baseKind, isActive })) }) }); const payload = await response.json() as { taskTypes?: TaskTypeDraft[]; message?: string }; if (!response.ok || !payload.taskTypes) throw new Error(payload.message || "Не удалось сохранить типы задач"); setItems(payload.taskTypes); setSaved(payload.taskTypes); onNotify("Типы задач сохранены"); } catch (error) { onNotify(error instanceof Error ? error.message : "Не удалось сохранить типы задач"); } finally { setSaving(false); } }
  return <main><PageIntro eyebrow="Рабочий процесс" title="Типы задач" description="Единый список действий для задач, календаря и фильтров CRM." /><section className={styles.moduleEditor}><header><div className={styles.moduleTitle}><i>✓</i><span><small>Настраивается для всей команды</small><strong>Действия сотрудников</strong></span></div></header><div className={styles.fieldHeader}><div><strong>Доступные типы</strong><span>Архивный тип остаётся у старых задач, но не предлагается в новых.</span></div><button type="button" disabled={loading || items.length >= 20} onClick={() => setItems((current) => [...current, { key: `new-${crypto.randomUUID()}`, name: "Новый тип", baseKind: "OTHER", position: current.length, isActive: true, taskCount: 0 }])}>＋ Добавить тип</button></div>{loading ? <div className={styles.editorState}>Загружаем типы задач…</div> : <div className={`${styles.fieldList} ${styles.taskTypeList}`}>{items.map((item, index) => <div key={item.id || item.key}><span className={styles.drag}>⠿</span><input value={item.name} aria-label={`Название типа ${index + 1}`} onChange={(event) => setItems((current) => current.map((value) => value === item ? { ...value, name: event.target.value } : value))} /><select value={item.baseKind} aria-label={`Поведение типа ${item.name}`} onChange={(event) => setItems((current) => current.map((value) => value === item ? { ...value, baseKind: event.target.value as ApiTaskKind } : value))}>{Object.entries(taskKindLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><span className={styles.fieldType}>{item.taskCount ? `${item.taskCount} задач` : "Не использован"}</span><div className={styles.rowActions}><button type="button" disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button type="button" disabled={index === items.length - 1} onClick={() => move(index, 1)}>↓</button><button className={styles.archiveTypeButton} type="button" onClick={() => setItems((current) => current.map((value) => value === item ? { ...value, isActive: !value.isActive } : value))}>{item.isActive ? "В архив" : "Вернуть"}</button></div></div>)}</div>}{changed && <footer><button type="button" onClick={() => setItems(saved)}>Отменить</button><button className={styles.footerSaveButton} type="button" disabled={saving || items.some((item) => !item.name.trim())} onClick={() => { void save(); }}>{saving ? "Сохраняем…" : "Сохранить изменения"}</button></footer>}</section></main>;
}

function WorkspaceSettings({ onNotify }: { onNotify: (message: string) => void }) {
  const empty = { name: "", companyName: "", phone: "", email: "", timezone: "Europe/Madrid", currency: "USD" }; const [form, setForm] = useState(empty); const [saved, setSaved] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const changed = JSON.stringify(form) !== JSON.stringify(saved);
  useEffect(() => { let active = true; void fetch("/api/crm/settings", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { workspace?: typeof empty; message?: string }; if (!response.ok || !payload.workspace) throw new Error(payload.message); if (active) { const next = { ...payload.workspace, companyName: payload.workspace.companyName || "", phone: payload.workspace.phone || "", email: payload.workspace.email || "" }; setForm(next); setSaved(next); } }).catch(() => onNotify("Не удалось загрузить рабочее пространство")).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [onNotify]);
  async function save() { setSaving(true); try { const response = await fetch("/api/crm/settings/workspace", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, companyName: form.companyName || null, phone: form.phone || null, email: form.email || null }) }); const payload = await response.json() as typeof empty & { message?: string }; if (!response.ok) throw new Error(payload.message || "Не удалось сохранить настройки"); const next = { ...payload, companyName: payload.companyName || "", phone: payload.phone || "", email: payload.email || "" }; setForm(next); setSaved(next); onNotify("Рабочее пространство сохранено"); } catch (error) { onNotify(error instanceof Error ? error.message : "Не удалось сохранить настройки"); } finally { setSaving(false); } }
  return <main><PageIntro eyebrow="Основное" title="Рабочее пространство" description="Название агентства, рабочие контакты и региональные параметры CRM." />{loading ? <div className={styles.editorState}>Загружаем настройки…</div> : <><FormSection title="О компании"><div className={styles.formGrid}><ControlledField label="Название пространства" value={form.name} onChange={(name) => setForm((current) => ({ ...current, name }))} /><ControlledField label="Название агентства" value={form.companyName} onChange={(companyName) => setForm((current) => ({ ...current, companyName }))} /><ControlledField label="Рабочий телефон" value={form.phone} onChange={(phone) => setForm((current) => ({ ...current, phone }))} /><ControlledField label="Email компании" type="email" value={form.email} onChange={(email) => setForm((current) => ({ ...current, email }))} /></div></FormSection><FormSection title="Регион и формат"><div className={styles.formGrid}><ControlledSelect label="Часовой пояс" value={form.timezone} options={[{ value: "Europe/Madrid", label: "Europe/Madrid" }, { value: "Europe/Kyiv", label: "Europe/Kyiv" }, { value: "UTC", label: "UTC" }]} onChange={(timezone) => setForm((current) => ({ ...current, timezone }))} /><ControlledSelect label="Валюта" value={form.currency} options={[{ value: "USD", label: "USD — $" }, { value: "EUR", label: "EUR — €" }, { value: "UAH", label: "UAH — ₴" }]} onChange={(currency) => setForm((current) => ({ ...current, currency }))} /></div></FormSection>{changed && <SaveBar saving={saving} onCancel={() => setForm(saved)} onSave={() => { void save(); }} />}</>}</main>;
}

function IntegrationSettings() {
  const [states, setStates] = useState<IntegrationState[]>([]); const [loading, setLoading] = useState(true); const [loadFailed, setLoadFailed] = useState(false);
  useEffect(() => { let active = true; void fetch("/api/crm/integrations", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { connections?: IntegrationState[] }; if (!response.ok || !payload.connections) throw new Error(); if (active) setStates(payload.connections); }).catch(() => { if (active) setLoadFailed(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const cards = [{ provider: "META_LEAD_ADS", name: "Meta Lead Ads", description: "Входящие обращения через защищённый маршрут Google Sheets." }, { provider: "TELEGRAM", name: "Telegram", description: "Персональные уведомления сотрудников о лидах и задачах." }];
  return <main><PageIntro eyebrow="Коммуникации" title="Интеграции" description="Состояние подключённых каналов и быстрый переход к их управлению." />{loadFailed && <div className={styles.inlineError}>Не удалось проверить состояние интеграций. Управление ими по-прежнему доступно в основном разделе.</div>}<section className={styles.settingsCards}>{cards.map((card) => { const state = states.find((item) => item.provider === card.provider); const connected = state?.status === "CONNECTED" && state.enabled; return <article key={card.provider}><span className={connected ? styles.statusReady : styles.statusMuted}>{loading ? "Проверяем" : connected ? "Подключено" : "Не подключено"}</span><h3>{card.name}</h3><p>{card.description}</p><small>{state?.lastEventAt ? `Последнее событие: ${new Date(state.lastEventAt).toLocaleString("ru-RU")}` : state?.lastError || "Событий пока нет"}</small><Link href="/integrations">Настроить интеграцию →</Link></article>; })}<article className={styles.plannedCard}><span className={styles.statusMuted}>Планируется</span><h3>Instagram и телефония</h3><p>Появятся после подключения реальных реквизитов провайдеров.</p><small>Фиктивные подключения не создаются.</small></article></section></main>;
}

function TeamAccessSettings() { return <main><PageIntro eyebrow="Команда" title="Участники и роли" description="Системные роли, приглашения и доступ сотрудников к рабочим данным." /><section className={styles.roleCards}><article><span>Полный контроль</span><h3>Администратор</h3><p>Настраивает CRM, интеграции, команду и видит все рабочие данные.</p></article><article><span>Управление командой</span><h3>Руководитель</h3><p>Работает с данными своей команды, сотрудниками и уведомлениями.</p></article><article><span>Работа с клиентами</span><h3>Менеджер</h3><p>Видит собственные сделки, задачи и общую очередь новых обращений.</p></article></section><div className={styles.linkCard}><span><strong>Управление сотрудниками</strong><small>Приглашения, назначение ролей и отключение доступа выполняются в разделе команды.</small></span><Link href="/team?tab=people">Открыть участников →</Link></div><div className={styles.linkCard}><span><strong>Матрица системных прав</strong><small>Права ролей зафиксированы продуктом и не изображаются редактируемыми чекбоксами.</small></span><Link href="/team?tab=roles">Посмотреть роли →</Link></div></main>; }

function NotificationsSettings() {
  const [members, setMembers] = useState<TeamMemberSummary[]>([]); const [loading, setLoading] = useState(true); const [loadFailed, setLoadFailed] = useState(false);
  useEffect(() => { let active = true; void fetch("/api/crm/team", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { members?: TeamMemberSummary[] }; if (!response.ok || !payload.members) throw new Error(); if (active) setMembers(payload.members); }).catch(() => { if (active) setLoadFailed(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  return <main><PageIntro eyebrow="Коммуникации" title="Уведомления" description="Выберите сотрудника и настройте, какие события Telegram отправляет именно ему." />{loading ? <div className={styles.editorState}>Загружаем сотрудников…</div> : loadFailed ? <div className={styles.inlineError}>Список сотрудников недоступен. Проверьте доступ к управлению командой.</div> : <section className={styles.memberSettingsList}>{members.filter((member) => member.status === "ACTIVE").map((member) => <article key={member.id}><span className={styles.memberAvatar}>{member.name.slice(0, 1).toLocaleUpperCase("ru")}</span><div><strong>{member.name}</strong><small>{member.email} · {roleLabels[member.role]}</small></div><Link href={`/team?member=${member.id}&memberTab=access`}>Настроить уведомления →</Link></article>)}</section>}<section className={styles.explanationBox}><strong>Как работает охват</strong><p>«Вся команда» — выбранные события по всем сотрудникам. «Только свои» — только собственные лиды и задачи. «Выбранные сотрудники» — события конкретных коллег. «Не присылать» полностью отключает Telegram-уведомления.</p></section></main>;
}

function SecuritySettings({ onNotify }: { onNotify: (message: string) => void }) {
  const [sessions, setSessions] = useState<Array<{ id: string; current: boolean; device: string; browser: string; ipAddress: string | null; lastSeenAt: string }>>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(() => fetch("/api/crm/settings/sessions", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { sessions?: typeof sessions }; if (!response.ok || !payload.sessions) throw new Error(); setSessions(payload.sessions); }).catch(() => onNotify("Не удалось загрузить активные сеансы")).finally(() => setLoading(false)), [onNotify]); useEffect(() => { void load(); }, [load]);
  async function revoke(sessionId: string) { const response = await fetch(`/api/crm/settings/sessions/${sessionId}`, { method: "DELETE" }); if (!response.ok) return onNotify("Не удалось завершить сеанс"); onNotify("Сеанс завершён"); await load(); }
  async function revokeOthers() { const response = await fetch("/api/crm/settings/sessions/revoke-others", { method: "POST" }); if (!response.ok) return onNotify("Не удалось завершить другие сеансы"); onNotify("Другие сеансы завершены"); await load(); }
  return <main><PageIntro eyebrow="Система" title="Безопасность" description="Доступ к аккаунту и устройства, на которых открыта CRM." /><section className={styles.plannedFeatures}><article><span>Следующий этап</span><strong>Смена пароля</strong><p>Отдельный защищённый сценарий с подтверждением текущего пароля.</p></article><article><span>Следующий этап</span><strong>Двухфакторная авторизация</strong><p>Подтверждение входа одноразовым кодом. Элемент управления появится вместе с рабочей функцией.</p></article></section><FormSection title="Активные сеансы">{loading ? <div className={styles.editorState}>Загружаем сеансы…</div> : sessions.map((session) => <div className={styles.session} key={session.id}><i>▯</i><span><strong>{session.device} · {session.browser}</strong><small>{session.ipAddress || "Адрес не определён"} · {new Date(session.lastSeenAt).toLocaleString("ru-RU")}</small></span>{session.current ? <b>Сейчас</b> : <button type="button" onClick={() => { void revoke(session.id); }}>Завершить</button>}</div>)}<button className={styles.dangerText} type="button" disabled={!sessions.some((session) => !session.current)} onClick={() => { void revokeOthers(); }}>Выйти на всех других устройствах</button></FormSection></main>;
}

function DataSettings() { return <main><PageIntro eyebrow="Система" title="Данные" description="Рабочий обмен данными CRM без выдуманных документов и реквизитов." /><section className={styles.settingsCards}><article><span className={styles.statusReady}>Работает</span><h3>Импорт и экспорт сделок</h3><p>CSV и Excel с техническими идентификаторами для безопасного обратного импорта.</p><Link href="/?transfer=1">Открыть импорт и экспорт →</Link></article><article className={styles.plannedCard}><span className={styles.statusMuted}>Следующий этап</span><h3>Полный экспорт CRM</h3><p>Единый архив контактов, сделок, задач, объектов и истории.</p></article><article className={styles.plannedCard}><span className={styles.statusMuted}>Следующий этап</span><h3>Резервные копии</h3><p>Регулярные снимки базы и проверяемое восстановление данных.</p></article></section></main>; }

function ProfileSettings({ onNotify }: { onNotify: (message: string) => void }) {
  const empty = { name: "", email: "", phone: "" }; const [profile, setProfile] = useState(empty); const [saved, setSaved] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const changed = JSON.stringify(profile) !== JSON.stringify(saved);
  useEffect(() => { let active = true; void fetch("/api/crm/settings", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { profile?: typeof empty }; if (!response.ok || !payload.profile) throw new Error(); if (active) { const next = { ...payload.profile, phone: payload.profile.phone || "" }; setProfile(next); setSaved(next); } }).catch(() => onNotify("Не удалось загрузить профиль")).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [onNotify]);
  async function save() { setSaving(true); try { const response = await fetch("/api/crm/settings/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: profile.name, phone: profile.phone || null }) }); const payload = await response.json() as typeof empty & { message?: string }; if (!response.ok) throw new Error(payload.message || "Не удалось сохранить профиль"); const next = { ...payload, phone: payload.phone || "" }; setProfile(next); setSaved(next); onNotify("Профиль сохранён"); } catch (error) { onNotify(error instanceof Error ? error.message : "Не удалось сохранить профиль"); } finally { setSaving(false); } }
  const initials = useMemo(() => profile.name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "—", [profile.name]);
  return <main><PageIntro eyebrow="Личное" title="Мой профиль" description="Контактные данные текущего пользователя CRM." />{loading ? <div className={styles.editorState}>Загружаем профиль…</div> : <><section className={styles.profileHeader}><div className={styles.profileAvatar}>{initials}</div><span><strong>{profile.name}</strong><small>{profile.email}</small></span><span className={styles.plannedLabel}>Фото появится вместе с загрузкой файлов</span></section><FormSection title="Контактные данные"><div className={styles.formGrid}><ControlledField label="Имя и фамилия" value={profile.name} onChange={(name) => setProfile((current) => ({ ...current, name }))} /><ControlledField label="Телефон" value={profile.phone} onChange={(phone) => setProfile((current) => ({ ...current, phone }))} /><ControlledField label="Email" type="email" value={profile.email} readOnly onChange={() => undefined} /></div></FormSection>{changed && <SaveBar saving={saving} onCancel={() => setProfile(saved)} onSave={() => { void save(); }} />}</>}</main>;
}

function FormSection({ title, children }: { title: string; children: ReactNode }) { return <section className={styles.formSection}><h3>{title}</h3>{children}</section>; }
function ControlledField({ label, value, type = "text", readOnly = false, onChange }: { label: string; value: string; type?: string; readOnly?: boolean; onChange: (value: string) => void }) { return <label className={styles.field}><span>{label}</span><input type={type} value={value} readOnly={readOnly} onChange={(event) => onChange(event.target.value)} /></label>; }
function ControlledSelect({ label, value, options, onChange }: { label: string; value: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void }) { return <label className={styles.field}><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label>; }
function SaveBar({ saving, onCancel, onSave }: { saving: boolean; onCancel: () => void; onSave: () => void }) { return <div className={styles.saveBar}><span>Есть несохранённые изменения</span><button className={styles.cancelButton} type="button" disabled={saving} onClick={onCancel}>Отменить</button><button type="button" disabled={saving} onClick={onSave}>{saving ? "Сохраняем…" : "Сохранить"}</button></div>; }
