"use client";

import { useEffect, useMemo, useState } from "react";
import type { DevelopmentAssetRecord } from "@/types/developments";
import styles from "./developments.module.css";

type Field = "unitNumber" | "building" | "section" | "floor" | "rooms" | "area" | "price" | "pricePerSquareMeter" | "currency" | "status" | "renovationType" | "renovationCompletion" | "note";
type Mapping = Record<number, Field | "">;
type ParsedSheet = { name: string; rows: string[][]; columns: number };
type Block = { id: string; label: string; headerRow: number; headers: string[]; rows: Array<{ rowNumber: number; cells: string[] }>; mapping: Mapping; selected: boolean };
type Preview = { rows: Array<{ rowNumber: number; unitNumber: string; building: string | null; section: string | null; action: "CREATE" | "UPDATE" | "REVIEW"; warnings: string[]; errors: string[] }>; counts: { create: number; update: number; review: number } };

const fields: Array<{ value: Field; label: string }> = [
  { value: "unitNumber", label: "№ квартиры / помещения" }, { value: "building", label: "Корпус / дом" }, { value: "section", label: "Секция / подъезд" },
  { value: "floor", label: "Этаж" }, { value: "rooms", label: "Комнаты / тип" }, { value: "area", label: "Площадь, м²" },
  { value: "pricePerSquareMeter", label: "Цена за м²" }, { value: "price", label: "Общая цена" }, { value: "currency", label: "Валюта" },
  { value: "status", label: "Статус" }, { value: "renovationType", label: "Тип ремонта" }, { value: "renovationCompletion", label: "Срок ремонта" }, { value: "note", label: "Примечание" },
];
const labelFor = (value: Field) => fields.find((field) => field.value === value)?.label ?? value;
function normalize(value: string) { return value.trim().toLocaleLowerCase("ru").replace(/ё/g, "е").replace(/[.,()_\-/]+/g, " ").replace(/\s+/g, " "); }
function recognizeHeader(value: string): Field | "" {
  const key = normalize(value); if (!key) return "";
  if (/номер.*кварт|№.*кварт|квартир|картир|апартамент|unit/.test(key)) return "unitNumber";
  if (/корпус|дом|building/.test(key)) return "building"; if (/секци|подъезд|section/.test(key)) return "section";
  if (/этаж|floor/.test(key)) return "floor"; if (/комнат|rooms/.test(key)) return "rooms"; if (/метраж|площад|area|м²|м2/.test(key)) return "area";
  if (/цен.*м ?кв|цен.*м²|цен.*м2|price.*m2/.test(key)) return "pricePerSquareMeter"; if (/общ.*цен|100%|стоимост|total.*price/.test(key)) return "price";
  if (/валют|currency/.test(key)) return "currency"; if (/статус|состояни|status/.test(key)) return "status";
  if (/срок.*ремонт|окончан.*ремонт/.test(key)) return "renovationCompletion"; if (/тип.*ремонт|ремонт/.test(key)) return "renovationType";
  if (/примеч|коммент|note/.test(key)) return "note"; return "";
}
function mapHeaders(headers: string[], sampleRows: string[][]): Mapping {
  const used = new Set<Field>(); const mapping: Mapping = {};
  headers.forEach((header, index) => { const field = recognizeHeader(header); mapping[index] = field && !used.has(field) ? field : ""; if (mapping[index]) used.add(mapping[index] as Field); });
  headers.forEach((header, index) => { if (header.trim() || mapping[index]) return; const examples = sampleRows.slice(0, 20).map((row) => normalize(row[index] ?? "")).filter(Boolean); if (examples.length && examples.filter((value) => /аванс|спс|коммент|бронь/.test(value)).length >= Math.min(2, examples.length)) mapping[index] = "note"; });
  return mapping;
}
function headerScore(row: string[]) { const fieldsFound = new Set(row.map(recognizeHeader).filter(Boolean)); return fieldsFound.has("unitNumber") && fieldsFound.has("floor") && fieldsFound.size >= 3; }
function labelBefore(rows: string[][], headerIndex: number, fallback: string) { for (let index = headerIndex - 1; index >= Math.max(0, headerIndex - 6); index -= 1) { const values = rows[index]!.filter((cell) => cell.trim()); if (values.length === 1 && !/квартир.*ремонт|с богом/i.test(values[0]!)) return values[0]!.trim(); } return fallback; }
function relevantByName(label: string, projectName: string, onlyBlock: boolean) {
  if (onlyBlock) return true; const project = normalize(projectName); const source = normalize(label); if (project.includes(source) || source.includes(project)) return true;
  const range = project.match(/(\d+)\s+(\d+)/); const number = source.match(/\d+/); return Boolean(range && number && Number(number[0]) >= Number(range[1]) && Number(number[0]) <= Number(range[2]));
}
function detectBlocks(sheet: ParsedSheet, projectName: string): Block[] {
  const headerIndexes = sheet.rows.map((row, index) => headerScore(row) ? index : -1).filter((index) => index >= 0);
  return headerIndexes.map((headerIndex, position) => { const next = headerIndexes[position + 1] ?? sheet.rows.length; const headers = sheet.rows[headerIndex]!.map((value, index) => value.trim() || `Колонка ${index + 1}`); const candidates = sheet.rows.slice(headerIndex + 1, next).map((cells, offset) => ({ rowNumber: headerIndex + offset + 2, cells })).filter(({ cells }) => cells.filter((cell) => cell.trim()).length >= 2); const mapping = mapHeaders(headers, candidates.map((row) => row.cells)); const unitColumn = Number(Object.entries(mapping).find(([, field]) => field === "unitNumber")?.[0] ?? -1); const rows = candidates.filter(({ cells }) => unitColumn >= 0 && Boolean(cells[unitColumn]?.trim())); const label = labelBefore(sheet.rows, headerIndex, `${sheet.name}, строки ${headerIndex + 1}–${next}`); return { id: `${sheet.name}:${headerIndex}`, label, headerRow: headerIndex + 1, headers, rows, mapping, selected: false }; }).map((block, _index, all) => ({ ...block, selected: relevantByName(block.label, projectName, all.length === 1) }));
}

export function DevelopmentImportWizard({ projectId, projectName, asset, initialView = "import", onClose, onPublished }: { projectId: string; projectName: string; asset: DevelopmentAssetRecord; initialView?: "source" | "import"; onClose: () => void; onPublished: () => Promise<void> }) {
  const [sheets, setSheets] = useState<ParsedSheet[]>([]); const [sheetIndex, setSheetIndex] = useState(0); const [blocks, setBlocks] = useState<Block[]>([]); const [view, setView] = useState<"source" | "import">(initialView);
  const [defaults, setDefaults] = useState({ currency: "USD", status: "AVAILABLE" }); const [preview, setPreview] = useState<Preview | null>(null); const [confirmed, setConfirmed] = useState<number[]>([]);
  const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [manualHeader, setManualHeader] = useState(1); const sheet = sheets[sheetIndex];
  useEffect(() => { let active = true; void (async () => { try { const response = await fetch(`/api/crm/development-projects/${projectId}/assets/${asset.id}/source`, { cache: "no-store" }); if (!response.ok) throw new Error("Не удалось прочитать файл из хранилища."); const XLSX = await import("xlsx"); const workbook = XLSX.read(await response.arrayBuffer(), { type: "array" }); const parsed = workbook.SheetNames.flatMap((name) => { const worksheet = workbook.Sheets[name]; if (!worksheet) return []; const values = XLSX.utils.sheet_to_json<unknown[]>(worksheet, { header: 1, defval: "", raw: false, blankrows: true }); const columns = Math.max(0, ...values.map((row) => row.length)); const rows = values.map((row) => Array.from({ length: columns }, (_, index) => String(row[index] ?? ""))); return rows.some((row) => row.some((cell) => cell.trim())) ? [{ name, rows, columns }] : []; }); if (!parsed.length) throw new Error("В файле нет читаемых листов."); if (active) { setSheets(parsed); setBlocks(detectBlocks(parsed[0]!, projectName)); } } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : "Не удалось открыть Excel."); } finally { if (active) setBusy(false); } })(); return () => { active = false; }; }, [asset.id, projectId, projectName]);
  function selectSheet(next: number) { setSheetIndex(next); setBlocks(detectBlocks(sheets[next]!, projectName)); setPreview(null); setError(""); }
  function updateBlock(id: string, patch: Partial<Block>) { setBlocks((current) => current.map((block) => block.id === id ? { ...block, ...patch } : block)); }
  function addManualBlock() { if (!sheet) return; const headerIndex = Math.max(0, Math.min(sheet.rows.length - 1, manualHeader - 1)); const headers = sheet.rows[headerIndex]!.map((value, index) => value.trim() || `Колонка ${index + 1}`); const rows = sheet.rows.slice(headerIndex + 1).map((cells, offset) => ({ rowNumber: headerIndex + offset + 2, cells })).filter(({ cells }) => cells.filter((cell) => cell.trim()).length >= 2); const mapping = mapHeaders(headers, rows.map((row) => row.cells)); setBlocks([{ id: `${sheet.name}:manual:${headerIndex}`, label: `${sheet.name}, заголовки в строке ${manualHeader}`, headerRow: manualHeader, headers, rows, mapping, selected: true }]); setError(""); }
  function mappedRows() { return blocks.filter((block) => block.selected).flatMap((block) => { const unitColumn = Number(Object.entries(block.mapping).find(([, field]) => field === "unitNumber")?.[0] ?? -1); return block.rows.filter(({ cells }) => unitColumn >= 0 && Boolean(cells[unitColumn]?.trim())).map(({ rowNumber, cells }) => { const values: Partial<Record<Field, string>> = { ...defaults }; const raw = Object.fromEntries(block.headers.map((header, column) => [`${header} [${column + 1}]`, cells[column] ?? ""])); for (const [column, field] of Object.entries(block.mapping)) { if (!field) continue; const value = cells[Number(column)]?.trim(); if (value) values[field] = value; } if (blocks.length > 1 && !values.building) values.building = block.label; return { rowNumber, sourceSheet: `${asset.filename} · ${sheet?.name} · ${block.label}`.slice(0, 300), raw, values }; }); }); }
  async function check() { const rows = mappedRows(); if (!rows.length) { setError("Выберите хотя бы один распознанный блок с квартирами."); return; } setBusy(true); setError(""); try { const response = await fetch(`/api/crm/development-projects/${projectId}/assets/${asset.id}/import/preview`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ rows }) }); const payload = await response.json() as Preview & { message?: string }; if (!response.ok || !payload.rows) throw new Error(payload.message || "Не удалось проверить строки."); setPreview(payload); setConfirmed([]); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось проверить строки."); } finally { setBusy(false); } }
  async function publish() { setBusy(true); setError(""); try { const response = await fetch(`/api/crm/development-projects/${projectId}/assets/${asset.id}/import/publish`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmedRows: confirmed }) }); const payload = await response.json() as { message?: string }; if (!response.ok) throw new Error(payload.message || "Не удалось опубликовать шахматку."); await onPublished(); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось опубликовать шахматку."); } finally { setBusy(false); } }
  const selectedRows = useMemo(() => blocks.filter((block) => block.selected).reduce((sum, block) => sum + block.rows.length, 0), [blocks]); const warningsConfirmed = preview?.rows.every((row) => !row.warnings.length || confirmed.includes(row.rowNumber)) ?? false;
  return <div className={styles.importLayer} role="dialog" aria-modal="true"><div className={styles.importDialog}><header><div><span>ШАХМАТКА ИЗ EXCEL</span><h2>{preview ? "Проверьте результат" : view === "source" ? "Просмотр исходного файла" : "Что удалось распознать"}</h2><p>{asset.filename}</p></div><button type="button" onClick={onClose} aria-label="Закрыть">×</button></header>
    {!preview && <div className={styles.importTabs}><button className={view === "source" ? styles.activeImportTab : ""} type="button" onClick={() => setView("source")}>Исходная таблица</button><button className={view === "import" ? styles.activeImportTab : ""} type="button" onClick={() => setView("import")}>Нормализовать и импортировать</button></div>}
    <div className={styles.importBody}>{busy && !sheet ? <div className={styles.assetEmpty}>Читаем Excel…</div> : error && !sheet ? <div className={styles.importError}>{error}</div> : !preview && sheet && view === "source" ? <><div className={styles.sourceToolbar}>{sheets.length > 1 && <select value={sheetIndex} onChange={(event) => selectSheet(Number(event.target.value))}>{sheets.map((item, index) => <option value={index} key={item.name}>{item.name}</option>)}</select>}<span>{sheet.rows.length} строк · {sheet.columns} колонок</span></div><div className={styles.sourceGrid}><table><tbody>{sheet.rows.map((row, rowIndex) => <tr key={rowIndex}><th>{rowIndex + 1}</th>{row.map((cell, columnIndex) => <td key={columnIndex}>{cell}</td>)}</tr>)}</tbody></table></div></> : !preview && sheet ? <>
      <div className={styles.importDefaults}><label>Валюта по умолчанию<select value={defaults.currency} onChange={(event) => setDefaults((current) => ({ ...current, currency: event.target.value }))}><option value="USD">USD</option><option value="EUR">EUR</option><option value="UAH">UAH</option></select></label><label>Статус по умолчанию<select value={defaults.status} onChange={(event) => setDefaults((current) => ({ ...current, status: event.target.value }))}><option value="AVAILABLE">В продаже</option><option value="RESERVED">Резерв</option><option value="SOLD">Продано</option><option value="UNKNOWN">Неизвестно</option></select></label></div>
      {blocks.length ? <><p className={styles.detectedSummary}>Найдено блоков: <b>{blocks.length}</b>. Выбрано строк для текущего проекта «{projectName}»: <b>{selectedRows}</b>. Лишние блоки не будут импортированы.</p><div className={styles.detectedBlocks}>{blocks.map((block) => <article className={block.selected ? styles.selectedBlock : ""} key={block.id}><label><input type="checkbox" checked={block.selected} onChange={(event) => updateBlock(block.id, { selected: event.target.checked })} /><span><strong>{block.label}</strong><small>Заголовки: строка {block.headerRow} · квартир: {block.rows.length}</small></span><b>{block.selected ? `→ ${projectName}` : "Не импортировать"}</b></label><div>{Object.values(block.mapping).filter(Boolean).map((field) => <span key={field}>{labelFor(field as Field)}</span>)}</div><details><summary>Настроить колонки</summary><div className={styles.blockMapping}>{block.headers.map((header, index) => <label key={`${header}:${index}`}><span>{header}</span><select value={block.mapping[index] ?? ""} onChange={(event) => updateBlock(block.id, { mapping: { ...block.mapping, [index]: event.target.value as Field | "" } })}><option value="">Не импортировать</option>{fields.map((field) => <option value={field.value} key={field.value}>{field.label}</option>)}</select></label>)}</div></details></article>)}</div></> : <div className={styles.noBlocks}><strong>Автоматически найти таблицу квартир не удалось</strong><p>Файл всё равно доступен во вкладке «Исходная таблица». Если вы знаете строку с названиями колонок, укажите её вручную.</p><label>Строка заголовков<input type="number" min="1" max={sheet.rows.length} value={manualHeader} onChange={(event) => setManualHeader(Number(event.target.value))} /></label><button type="button" onClick={addManualBlock}>Использовать эту строку</button></div>}
    </> : preview ? <><div className={styles.importSummary}><div><strong>{preview.counts.create}</strong><span>новых</span></div><div><strong>{preview.counts.update}</strong><span>обновятся</span></div><div className={preview.counts.review ? styles.summaryDanger : ""}><strong>{preview.counts.review}</strong><span>с ошибками</span></div></div><div className={styles.importRows}>{preview.rows.map((row) => <article key={row.rowNumber}><div><strong>Строка {row.rowNumber} · № {row.unitNumber || "не указан"}</strong><span>{[row.building, row.section].filter(Boolean).join(" · ") || "Без корпуса и секции"} · {row.action === "CREATE" ? "новая" : row.action === "UPDATE" ? "обновление" : "нужно исправить"}</span></div>{row.errors.length > 0 && <p>{row.errors.join(" ")}</p>}{row.warnings.length > 0 && <label><input type="checkbox" checked={confirmed.includes(row.rowNumber)} onChange={(event) => setConfirmed((current) => event.target.checked ? [...current, row.rowNumber] : current.filter((number) => number !== row.rowNumber))} /><span>{row.warnings.join(" ")}</span></label>}</article>)}</div></> : null}{error && sheet && <p className={styles.importError}>{error}</p>}</div>
    <footer><button type="button" onClick={preview ? () => { setPreview(null); setConfirmed([]); setError(""); } : onClose}>{preview ? "Назад" : "Закрыть"}</button>{!preview && view === "source" && <button className={styles.primary} type="button" onClick={() => setView("import")}>Перейти к импорту</button>}{!preview && view === "import" && blocks.length > 0 && <button className={styles.primary} type="button" disabled={busy || selectedRows === 0} onClick={() => { void check(); }}>{busy ? "Проверяем…" : `Проверить ${selectedRows} строк`}</button>}{preview && <button className={styles.primary} type="button" disabled={busy || preview.counts.review > 0 || !warningsConfirmed} onClick={() => { void publish(); }}>{busy ? "Публикуем…" : "Подтвердить и опубликовать"}</button>}</footer>
  </div></div>;
}
